
services:
  nestjs-app:
    build: .
    container_name: nestjs-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 3000
    restart: always
